home_page:
  path: /
  methods: GET
  controller: App\Action\HomePageAction

sign_in_page:
  path: /sign-in
  methods: GET
  controller: App\Action\Accounts\SignInPageAction
  options:
    middleware:
      - 'App\Domain\Symfony\Middlewares\CheckGuestMiddleware'
      - 'App\Domain\Symfony\Middlewares\PermissionMiddleware'

sign_in:
  path: /sign-in
  methods: POST
  controller: App\Action\Accounts\SignInAction
  options:
    middleware:
      - 'App\Domain\Symfony\Middlewares\CheckGuestMiddleware'
      - 'App\Domain\Symfony\Middlewares\PermissionMiddleware'

register_page:
  path: /register
  methods: GET
  controller: App\Action\Accounts\RegisterPageAction
  options:
    middleware:
      - 'App\Domain\Symfony\Middlewares\CheckGuestMiddleware'
      - 'App\Domain\Symfony\Middlewares\PermissionMiddleware'

register:
  path: /register
  methods: POST
  controller: App\Action\Accounts\RegisterAction
  options:
    middleware:
      - 'App\Domain\Symfony\Middlewares\CheckGuestMiddleware'
      - 'App\Domain\Symfony\Middlewares\PermissionMiddleware'

logout:
  path: /logout
  methods: GET
  controller: App\Action\Accounts\LogoutAction
  options:
    middleware:
      - 'App\Domain\Symfony\Middlewares\CheckAuthMiddleware'
      - 'App\Domain\Symfony\Middlewares\PermissionMiddleware'

new_review_page:
  path: /songs/reviews/new
  methods: GET
  controller: App\Action\SongsReviews\NewReviewPageAction
  options:
    middleware:
      - 'App\Domain\Symfony\Middlewares\CheckAuthMiddleware'
      - 'App\Domain\Symfony\Middlewares\PermissionMiddleware'

new_review:
  path: /songs/reviews/new
  methods: POST
  controller: App\Action\SongsReviews\NewReviewAction
  options:
    middleware:
      - 'App\Domain\Symfony\Middlewares\CheckAuthMiddleware'
      - 'App\Domain\Symfony\Middlewares\PermissionMiddleware'

songs_reviews_artists_ajax:
  path: songs/reviews/ajax/artists
  methods: GET
  controller: App\Action\SongsReviews\Ajax\GetArtistsAction
  options:
    middleware:
      - 'App\Domain\Symfony\Middlewares\CheckAuthMiddleware'
      - 'App\Domain\Symfony\Middlewares\PermissionMiddleware'

songs_reviews_genres_ajax:
  path: songs/reviews/ajax/genres
  methods: GET
  controller: App\Action\SongsReviews\Ajax\GetGenresAction
  options:
    middleware:
      - 'App\Domain\Symfony\Middlewares\CheckAuthMiddleware'
      - 'App\Domain\Symfony\Middlewares\PermissionMiddleware'

review_songs:
  path: songs/reviews
  methods: GET
  controller: App\Action\SongsReviews\GetSongsForReview
  options:
    middleware:
      - 'App\Domain\Symfony\Middlewares\CheckAuthMiddleware'
      - 'App\Domain\Symfony\Middlewares\PermissionMiddleware'