parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/Kernel.php'

    App\Http\SymfonyHttpClient:
        arguments:
            $apiHost: '%env(API_HOST)%'

    App\Action\:
        resource: '../src/Action/'
        tags: ['controller.service_arguments']
